platform :ios, ‘8.0’
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
# ignore all warnings from all pods
inhibit_all_warnings!

target 'GSHexin' do

pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'

end